# Generated by Django 5.0.3 on 2024-03-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_veterinaryinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='veterinary',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='veterinaryinstance',
            options={'ordering': ['create_date']},
        ),
    ]
