# Generated by Django 5.0.3 on 2024-03-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_doctor_options_alter_veterinary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='specialties',
            options={'ordering': ['name']},
        ),
    ]
