# Generated by Django 5.0.3 on 2024-03-28 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_pet_owner_alter_veterinaryinstance_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaryinstance',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.doctor'),
        ),
        migrations.AlterField(
            model_name='veterinaryinstance',
            name='pet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.pet'),
        ),
        migrations.AlterField(
            model_name='veterinaryinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='veterinaryinstance',
            name='veterinary_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.veterinary'),
        ),
    ]
